### ISSUE TITLE
Bundler fails to find load libsodium.so in Docker

### ISSUE THREAD

**Issue by Quintasan** [cryptosphere/rbnacl-libsodium#11]
My GitLab CI constantly fails on the rspec stage. GitLab CI uses Docker on each stage of the build process.

```
$ bundle exec rake db:create
rake aborted!
LoadError: Could not open library 'sodium': sodium: cannot open shared object file: No such file or directory.
Could not open library 'libsodium.so': libsodium.so: cannot open shared object file: No such file or directory
/usr/local/bundle/gems/ffi-1.9.18/lib/ffi/library.rb:147:in `block in ffi_lib'
/usr/local/bundle/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `map'
/usr/local/bundle/gems/ffi-1.9.18/lib/ffi/library.rb:100:in `ffi_lib'
/usr/local/bundle/gems/rbnacl-4.0.2/lib/rbnacl/sodium.rb:14:in `extended'
/usr/local/bundle/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:13:in `extend'
/usr/local/bundle/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:13:in `<module:Version>'
/usr/local/bundle/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:9:in `<module:Sodium>'
/usr/local/bundle/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:7:in `<module:RbNaCl>'
/usr/local/bundle/gems/rbnacl-4.0.2/lib/rbnacl/sodium/version.rb:6:in `<top (required)>'
/usr/local/bundle/gems/rbnacl-4.0.2/lib/rbnacl.rb:6:in `require'
/usr/local/bundle/gems/rbnacl-4.0.2/lib/rbnacl.rb:6:in `<top (required)>'
/builds/project-0/config/application.rb:9:in `<top (required)>'
/builds/project-0/Rakefile:6:in `require_relative'
/builds/project-0/Rakefile:6:in `<top (required)>'
/usr/local/bundle/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/bundle:22:in `load'
/usr/local/bundle/bin/bundle:22:in `<main>'
(See full trace by running task with --trace)
```

My `.gitlab-ci.yml`
```
image: "ruby:2.3"

services:
  - postgres:9.6-alpine

variables:
  POSTGRES_USER: mobill
  POSTGRES_PASSWORD: mobill

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client libsodium18 -y )'
  - eval $(ssh-agent -s)
  - echo "${SSH_PRIVATE_KEY_BASE64}" |  tr -d ' ' | base64 --decode | ssh-add -
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - gem install --no-document bundler
  - bundle install

rubocop:
  stage: test
  script:
    - bundle exec rubocop

rspec:
  stage: test
  script:
    - bundle exec rake db:create
    - bundle exec rake db:migrate
    - bundle exec rake spec

staging:
  stage: deploy
  environment: staging
  only:
    - master
  script:
    - bundle exec cap production deploy
```

`Gemfile`
```
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails'
gem 'puma'
gem 'multi_json'
gem 'pg'
gem 'hamlit-rails'
gem 'turbolinks', '~> 5'
gem 'decent_exposure', '3.0.0'
gem 'jquery-rails'
gem 'uglifier'
gem 'therubyracer'
gem 'sidekiq'
group :development do
  gem "rbnacl"
  gem "rbnacl-libsodium"
  gem "bcrypt_pbkdf"
  gem 'capistrano', '~> 3.7', require: false
  gem 'capistrano-rails', '~> 1.2', require: false
  gem 'capistrano-rbenv', '~> 2.1'
  gem 'capistrano-bundler', require: false
  gem 'capistrano3-puma', require: false
  gem 'web-console', '~> 2.0'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'letter_opener'
  gem 'bundler-audit'
end

group :development, :test do
  gem 'pry'
  gem 'byebug'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'factory_girl_rails'
  gem 'rubocop', require: false
  gem 'spring'
  gem 'spring-watcher-listen'
  gem 'rails-controller-testing'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'listen'
  gem 'bullet'
end
```

What am I doing wrong?
